can:
  interface: "canalystii"  # or "socketcan" if using Linux SocketCAN
  channel: 0
  bitrate: 1000000

motors:
  - id: 1                    # Your motor's CAN ID (1-127)
    limit_spd: 3.0           # Max speed (rad/s)
    limit_cur: 3.0           # Max current (A)
    control_mode: 0          # 0=MIT, 1=Position, 2=Velocity, 3=Current
    max_distance: 3.0        # Max position limit
    raw_pos_zero: 0.0        # Calibration offset (set after calibration)
    flip: false              # Reverse direction if needed
    mit:
      kp: 5.0                # Position gain
      kd: 0.5                # Damping gain